author = 'author'
cache = 'cache'
content = 'content'
distance = 'distance'
font_size = 'font_size'
heading = 'heading'
opacity = 'opacity'
position = 'position'
radian = 'radian'
size = 'size'
subheading = 'subheading'
quote = 'quote'

style = 'style'
fill = 'fill'
transform = 'transform'
